replicaCount: 1

image:
  repository: hello-python-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

metrics:
  enabled: true
  path: /status
  port: 5000

readinessProbe:
  path: /status
  initialDelaySeconds: 3
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 30
  failureThreshold: 5

containerPort: 5000

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
