name: "[DEV] Kubernetes Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/k8s-*.yml'
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  helm-apply:
    name: k8s apply dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/github-actions-oidc-role
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install Metrics Server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      - name: Install Traefik
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update
          helm upgrade --install traefik traefik/traefik --namespace kube-system --create-namespace

      - name: Install Prometheus & Grafana
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
