name: "[DEV] Terraform Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'tf/**/*.tf'
      - 'tf/**/*.tfvars'
  workflow_dispatch:

jobs:
  terraform-apply:
    name: tf-apply-dev
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform -chdir=tf/envs/dev init

      - name: Terraform Apply
        run: terraform -chdir=tf/envs/dev apply -var-file=dev.tfvars -auto-approve
